//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class playSchedule
    {
        public int id { get; set; }
        public string dateStart { get; set; }
        public string weekly { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public string device { get; set; }
        public string voiceFile { get; set; }
        public string zone { get; set; }
        public string status { get; set; }
    }
}
