//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class soundInfo
    {
        public int C_id { get; set; }
        public string soundTitle { get; set; }
        public string soundDescription { get; set; }
        public string recordedBy { get; set; }
        public string dateCreate { get; set; }
    }
}
